Feature/377 create campaigns module
RoverPlatform/rover-ios pull request #379
Opened 2018-12-17 21:11 UTC by orospakr

2018-12-17 21:12 UTC, orospakr commented on Sources/UI/Notifications/Services/NotificationStore/NotificationStoreService.swift
> +//}
This remains only just for temporary reference, I'll be replacing it next PR with Core Data.

2018-12-17 21:26 UTC, seanrucker requested changes

2018-12-17 21:26 UTC, seanrucker commented on Sources/UI/Notifications/Services/NotificationStore/NotificationStoreService.swift
> +//}
👍

2018-12-17 21:26 UTC, seanrucker commented on Sources/UI/UIAssembler.swift
> +    public init(associatedDomains: [String] = [], urlSchemes: [String] = [], sessionKeepAliveTime: Int = 30, isLifeCycleTrackingEnabled: Bool = true, isVersionTrackingEnabled: Bool = true, appGroup:
Should `appGroup` and `influenceTime` still be in there?

2018-12-17 21:26 UTC, seanrucker commented on Sources/Campaigns/Extensions/UI.UNNotificationResponse.swift
>  extension UNNotificationResponse {
Comment should be `RoverCampaigns` and the filename should be `Campaigns.OSLog` not `UI.OSLog`.

2018-12-17 21:26 UTC, seanrucker commented on Sources/Campaigns/Extensions/UI.UNNotificationResponse.swift
>  extension UNNotificationResponse {
Also looks like the target is wrong.

2018-12-18 14:34 UTC, seanrucker commented on Sources/Campaigns/Extensions/UI.UNNotificationResponse.swift
>  extension UNNotificationResponse {
The comment in the header is wrong.

2018-12-18 14:35 UTC, seanrucker requested changes
The comment in the header of the Campaigns.UNNotificationResponse.swift file is wrong.

2018-12-18 15:10 UTC, seanrucker approved these changes

2018-12-18 15:11 UTC, merged