Feature/398 experience sync support
RoverPlatform/rover-ios pull request #408
Opened 2019-02-05 20:06 UTC by orospakr

2019-02-05 20:26 UTC, orospakr commented on Sources/Sync/SyncCoordinator/SyncCoordinatorService.swift
> +        if participants.isEmpty {
What do you think about this change? Does it break any assumptions that you can remember?

2019-02-08 18:23 UTC, seanrucker requested changes
The logic is super hard to reason about (my fault, not yours). I do think this can be greatly simplified if you took a fresh stab at it given the different set of constraints we're working with now (the set of participants is fixed and known by the coordinator). For example, the response could be a single defined type now instead of each participant decoding the data object into its own response.

That being said... I think we can leave this for now–with your confirmation its been tested and works as expected–and revisit it at a later time.

One thing I *would* like to address now is the public scope of the module. Right now the public API footprint is very big and I don't think it needs to be. I believe the only thing that needs to be public is a single method to initiate a sync and perhaps some configuration.

If we can tighten up the public scope of this module to that single method, then I'm fine to move on because it is essentially a block box that does its job and we can look at it again in the future if we decided it's warranted.

2019-02-11 08:31 UTC, orospakr commented on Sources/Sync/SyncAssembler.swift
> +        let syncCoordinator = resolver.resolve(SyncCoordinator.self) as! SyncCoordinatorService
What do you think of this downcast here?

2019-02-11 08:34 UTC, orospakr commented
@seanrucker addressed review regarding scoping.  But I agree that more refactoring here is possible.

(PS burning late night oil because insomnia, nothing heroic lol)

2019-02-11 15:04 UTC, seanrucker requested changes
Make these internal and we're good to go.

<img width="201" alt="image" src="https://user-images.githubusercontent.com/188337/52571833-63b35000-2de4-11e9-85f8-18dbe1f99b38.png">

2019-02-11 15:36 UTC, seanrucker approved these changes

2019-02-11 15:37 UTC, merged