Feature: Match Automated Campaigns from Events.
RoverPlatform/rover-ios pull request #412
Opened 2019-02-21 00:50 UTC by orospakr

This implements the entire spec for automated campaigns, including the Predicates.

@seanrucker you may be interested to know how I solved the NSPredicate validation crash issue: in lieu of attempting to validate all of the NSPredicate rules by dead-reckoning their validation logic myself (and it appears there lots of rules),  I decided to take what I think is a more robust approach I by writing an objc wrapper that handles such errors gracefully and treats them as non-matching, since Swift naturally can't catch them.

Resolves #389.  (mapping of Predicate to NSPredicate)
Resolves #409.

2019-02-21 15:35 UTC, orospakr commented on Sources/Sync/SyncCoordinator/SyncClient.swift
>      }
leaving this disabled until experiences endpoint is deployed on production.

2019-02-22 15:48 UTC, seanrucker commented on Sources/Sync/SyncCoordinator/Participants/CampaignSyncParticipant.swift
> +extension Array {
Could these be made fileprivate to avoid polluting the Array API?

2019-02-22 15:52 UTC, seanrucker commented on Sources/Sync/SyncCoordinator/SyncCoordinatorService.swift
> +    var observers = ObserverSet<UIBackgroundFetchResult>()
What is this used for?

2019-02-22 16:14 UTC, seanrucker requested changes
- Using FP for `automatedCampaignsMatching` has the following tradeoffs:
  - Inconsistent with the rest of the codebase
  - Foreign, confusing style for the majority of iOS developers
  - Eschews our DI framework, restricting a developers ability to customize any part of it
- Suggest merging the `automatedCampaignsMatching` and `queryPredicateForCampaignQueryableFilters` functions into the `CampaignEventObserver` class and naming it `AutomationEngine`. The dependencies of the current `CampaignEventObserver` class and the `automatedCampaignsMatching` function both share the same dependencies: `DeviceSnapshot` and `NSManagedObjectContext`. 
- The extensions approach found in the current `AutomationEngine.swift` is good and a familiar concept with iOS developers. Consider marking them fileprivate so the API of the extended objects is restricted and not globally polluted.
- Move Havesine into the new AutomationEngine class as static funcs and constants.
- EventPipeline was changed from using a simple wrapper around `NotificationCenter` to using the `ObserverSet` utility I created. We had discussed in the past that `ObserverSet` doesn't add anything we can't do with a simple convenience wrapper around observing `NotificationCenter`. We had planned to remove the use of `ObserverSet`, not the other way around.
- Do we still need the Campaign entity in our data model now that we have separate AutomatedCampaign and ScheduledCampaign types?
- Can we delete TEMPORARY.swift now that it is empty?

2019-02-22 21:32 UTC, orospakr commented
I decided to put the Campaign entity in as an abstract super entity that polymorphs to either the scheduled or automated variant.  It has already come in handy for having a Campaign ID (without extra type information) on my scheduled notifications in the upcoming PR.

2019-02-22 22:16 UTC, seanrucker requested changes
- Make the `automatedCampaignsMatching` function a static function on the `AutomatedCampaignsFilter` class. Perhaps even rename this to `CampaignsFilter` so it can house more static functions related to filtering campaigns in the future? Just a thought…
- Create a method on `AutomationEngine` named something similar (e.g. `func automatedCampaigns(matching event: Event)` which delegates out to `CampaignsFilter.automatedCampaignsMatching`. 
- This approach is a win for both of us. The  `automatedCampaignsMatching` function remains a pure function and factors out all the complex logic from the `AutomationEngine`. At the same time, if the developer wanted to change the way applicable campaigns are determined, they have an extension point on the engine. By making it a static func on a class it alleviates my concern around global functions being out of style with the rest of our SDK.
- Also make sure your header comments match the file names ;)

2019-02-25 15:05 UTC, orospakr commented
huh re the idea of bundling pure static funcs into a class, swiftlint had an opinion:

`Convenience Type Violation: Types used for hosting only static members should be implemented as a caseless enum to avoid instantiation. (convenience_type)`

I'll experiment with it. Interesting idea.

2019-02-25 17:03 UTC, seanrucker approved these changes

2019-02-26 01:58 UTC, merged