Fix Incorrect scroll edge appearance
RoverPlatform/rover-ios pull request #548
Opened 2021-12-17 21:43 UTC by Moux

Address iOS 15 changes to standard and scroll edge appearances for navigation bars.

2021-12-20 15:57 UTC, orospakr requested changes

2021-12-20 15:57 UTC, orospakr commented on Sources/UI/ScreenViewController.swift
> +        navigationBar.barTintColor = backgroundColor
does this change behaviour on iOS <15?

2021-12-21 15:15 UTC, orospakr commented on Sources/UI/ScreenViewController.swift
> +        navigationBar.barTintColor = backgroundColor
ah I get it now

2021-12-21 20:04 UTC, Moux commented
Results with 2020 Pro Bowl Vote:

Experience not scrolled:
<img width="458" alt="Screen Shot 2021-12-21 at 3 02 58 PM" src="https://user-images.githubusercontent.com/534891/146990955-e57051ae-4faf-4726-bc45-be5f8c0af69c.png">

Experience scrolled:

<img width="502" alt="Screen Shot 2021-12-21 at 3 03 08 PM" src="https://user-images.githubusercontent.com/534891/146990930-cc0c925d-103a-4070-89a1-f552166b5eb9.png">

2021-12-21 20:06 UTC, Moux commented
Results with Bill - Holiday Gift Guide Final:

Experience not scrolled:

<img width="502" alt="Screen Shot 2021-12-21 at 3 05 41 PM" src="https://user-images.githubusercontent.com/534891/146991184-d2c146a3-26d2-428c-9ba1-a7c122f4677c.png">

Experience scrolled:

<img width="502" alt="Screen Shot 2021-12-21 at 3 05 54 PM" src="https://user-images.githubusercontent.com/534891/146991215-bcea20c5-f9ec-42de-ae5c-a6d74417b143.png">

2022-01-04 18:19 UTC, orospakr approved these changes

2022-01-04 19:03 UTC, merged